INSERT INTO GAMES (ID, NAME, ABBREVIATION) VALUES (1, 'CARDFIGHT VANGUARD', 'CFV');
INSERT INTO GAMES (ID, NAME, ABBREVIATION) VALUES (2, 'MAGIC THE GATHERING', 'MTG');
INSERT INTO EXPANSION (ID, NAME, ABBREVIATION, RELEASE_DATE, RELEASED, GAME_ID) VALUES (1, 'D Booster Set 08: Minerva Rising', 'DBT08', {ts '2023-02-23 00.00.00'}, FALSE, 1);
INSERT INTO EXPANSION (ID, NAME, ABBREVIATION, RELEASE_DATE, RELEASED, GAME_ID) VALUES (2, 'La Guerra de los Hermanos', {ts '2022-11-15 00.00.00'}, TRUE, 2);
INSERT INTO PRODUCT (ID, NAME, RARITY, QUANTITY, IMAGE, EXPANSION_ID) VALUES (1, 'Peak Personage Stealth Rogue, Shojodoji', 'RRR', 10, null, 1);
INSERT INTO PRODUCT (ID, NAME, RARITY, QUANTITY, IMAGE, EXPANSION_ID) VALUES (2, 'Stealth Dragon, Unpreceden', 'RRR', 17, null, 1);
INSERT INTO PRODUCT (ID, NAME, RARITY, QUANTITY, IMAGE, EXPANSION_ID) VALUES (3, 'Silver Thorn Dragon Tamer, Luquier', 'RRR', 15, null, 1);